export const SUPABASE_URL = 'https://lifeczpvyqpffvmnjzrl.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZmVjenB2eXFwZmZ2bW5qenJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjU3ODUsImV4cCI6MjA3MjAwMTc4NX0.k-Ppi_8sRvP5mQWBrTLF_n2ZLR6oADSvOg0uEZLNIDg';
export const CLICKER_ID = 'global';
